// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectARTEMIS.Infrastructure.Persistence;

#nullable disable

namespace ProjectARTEMIS.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260613180305_changedomaifna")]
    partial class changedomaifna
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlayerOnlineStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId");

                    b.ToTable("PlayerOnlineStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4487f4a-1bb6-72fa-bd04-9f5639fb04af"),
                            PlayerProfileId = new Guid("b2265d2e-9ff4-50ed-9b82-7d3417e9828d"),
                            StartTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        });
                });

            modelBuilder.Entity("PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicturePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PlayerProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2265d2e-9ff4-50ed-9b82-7d3417e9828d"),
                            Bio = "Project ARTEMIS Head System Administrator.",
                            Note = "",
                            ProfilePicturePath = "",
                            RealName = "Alex Sam Cabildo",
                            SchoolId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UserId = new Guid("a1154c1d-8ee3-49dc-8a71-6c2306d8717c")
                        });
                });

            modelBuilder.Entity("PlayerProfileStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId");

                    b.ToTable("PlayerProfileStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3376e3f-0aa5-61fe-ac93-8e4528fa939e"),
                            Message = "Profile initialized.",
                            PlayerProfileId = new Guid("b2265d2e-9ff4-50ed-9b82-7d3417e9828d"),
                            StartTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        });
                });

            modelBuilder.Entity("School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ColorCode = "#006633",
                            Description = "One of the oldest and most prestigious universities in Cebu, known for its rigorous academic programs and sprawling campuses.",
                            Name = "University of San Carlos (USC)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ColorCode = "#800000",
                            Description = "Renowned for its excellence in engineering, technology, and producing top-notch board exam placers (Home of the Technologians).",
                            Name = "Cebu Institute of Technology – University (CIT-U)"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ColorCode = "#003366",
                            Description = "A highly respected Catholic institution known for outstanding business, IT, and engineering courses.",
                            Name = "University of San Jose – Recoletos (USJ-R)"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ColorCode = "#7B1113",
                            Description = "The premier state university in the region, highly recognized for its competitive arts, design, and computer science programs.",
                            Name = "University of the Philippines Cebu (UP Cebu)"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            ColorCode = "#FFFFFF",
                            Description = "A top-tier medical and health sciences institution located near North Reclamation Area, producing world-class medical professionals.",
                            Name = "Cebu Doctors' University (CDU)"
                        });
                });

            modelBuilder.Entity("SocialMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SocialMedias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1198a5b-2cc7-83fa-cd05-8f674afb05bf"),
                            Name = "Facebook"
                        },
                        new
                        {
                            Id = new Guid("f22a9b6c-3dd8-94fa-de06-9f785b0c16cf"),
                            Name = "X (Twitter)"
                        },
                        new
                        {
                            Id = new Guid("f33bc77d-4ee9-05fa-ef07-af896c1d27df"),
                            Name = "Discord"
                        },
                        new
                        {
                            Id = new Guid("f44cd88e-5ff0-16fa-f008-bf9a7d2e38ef"),
                            Name = "Instagram"
                        },
                        new
                        {
                            Id = new Guid("f55de99f-6fa1-27fa-f109-cfab8e3f49ff"),
                            Name = "TikTok"
                        });
                });

            modelBuilder.Entity("SocialMediaHandle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SocialMediaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId");

                    b.ToTable("SocialMediaHandles");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1154c1d-8ee3-49dc-8a71-6c2306d8717c"),
                            IsAdmin = true,
                            PasswordHash = "$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
                            Username = "Spinelly"
                        });
                });

            modelBuilder.Entity("WhitelistRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FacebookUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WhitelistRequests");
                });

            modelBuilder.Entity("WhitelistRequestStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WhitelistRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WhitelistRequestId");

                    b.ToTable("WhitelistRequestStatuses");
                });

            modelBuilder.Entity("PlayerOnlineStatus", b =>
                {
                    b.HasOne("PlayerProfile", null)
                        .WithMany("OnlineStatuses")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayerProfileStatus", b =>
                {
                    b.HasOne("PlayerProfile", null)
                        .WithMany("ProfileStatuses")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMediaHandle", b =>
                {
                    b.HasOne("PlayerProfile", null)
                        .WithMany("LinkedSocials")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhitelistRequestStatus", b =>
                {
                    b.HasOne("WhitelistRequest", null)
                        .WithMany("Statuses")
                        .HasForeignKey("WhitelistRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayerProfile", b =>
                {
                    b.Navigation("LinkedSocials");

                    b.Navigation("OnlineStatuses");

                    b.Navigation("ProfileStatuses");
                });

            modelBuilder.Entity("WhitelistRequest", b =>
                {
                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
